---
services:
  myjenkins:

# Here it will directly create image from dockerfile and it wll directly use customised image from local storage
# Here I am using dockerfile9
    build: .
    ports:
      - 8888:8080
    networks:
      - abc

  mytomcat:
# Here it will pull image from docker hub public registry
    image: tomee
    ports:
      - 7777:8080
    networks:
      - xyz

networks:
  abc: {}
  xyz: {}

...
